apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: k8s-deployment 
spec: 
  selector: 
    matchLabels: 
      app: application 
  replicas: 3 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: application
    spec: 
      containers: 
      - name: application
        image: ovaledge000/application
        ports: 
        - containerPort: 8080
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: application-service 
spec: 
  selector: 
    app: application
  ports: 
  - protocol: TCP 
    port: 8080
    targetPort: 8080
  type: LoadBalancer 
