apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovaledge
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       —name: ovaledge1
          image: ovaledge000/oeimage:latest
          ports:
           —containerPort: 8080
